columns:
- Unnamed0
- app_id
- app_name
- review_id
- language
- review
- timestamp_created
- timestamp_updated
- recommended
- votes_helpful
- votes_funny
- weighted_vote_score
- comment_count
- steam_purchase
- received_for_free
- written_during_early_access
- authorsteamid
- authornum_games_owned
- authornum_reviews
- authorplaytime_forever
- authorplaytime_last_two_weeks
- authorplaytime_at_review
- authorlast_played
separator: '|'
